name: Terraform CI

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  terraform:
    name: Terraform Plan and Apply
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./terraform

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      TF_VAR_google_client_id: ${{ secrets.GOOGLE_CLIENT_ID }}
      TF_VAR_google_client_secret: ${{ secrets.GOOGLE_CLIENT_SECRET }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.5

      - name: Terraform Init
        run: terraform -chdir=envs/dev init

      - name: Terraform Validate
        run: terraform -chdir=envs/dev validate

      - name: Terraform Plan
        run: terraform -chdir=envs/dev plan -no-color -input=false -out=tfplan

      - name: Terraform Apply (Manual Trigger Only)
        if: github.event_name == 'workflow_dispatch'
        run: terraform -chdir=envs/dev apply -auto-approve tfplan
